### ISSUE TITLE
Not Found  The requested URL /googleshopping/oauth2callback was not found on this server.

### ISSUE THREAD

**Issue by ackmedikal** [thelia-modules/GoogleShopping#1]
Not Found

The requested URL /googleshopping/oauth2callback was not found on this server.
not the module configuration

**Comment by gillesbourgeat** [comment]
Hello,
The URL rewriting is enabled on your server ?

**Comment by ackmedikal** [comment]
no

**Comment by ackmedikal** [comment]
15 minute

**Comment by gillesbourgeat** [comment]
Configuration for Nginx
http://doc.thelia.net/en/documentation/configuration/server.html
