### ISSUE TITLE
php error on cron url 

### ISSUE THREAD

**Issue by ngweb37** [thelia-modules/GoogleShopping#2]
http://www.mydomain.com/admin/module/googleshopping/sync/catalog/a98f6923815ddfbb721c1a99932ba3d9

Fatal error: Class 'Google_Client' not found in /home/gelink/www/v2/local/modules/GoogleShopping/Handler/GoogleShoppingHandler.php on line 69

**Comment by lopes-vincent** [comment]
I think the php GoogleApiClient is missing in your project. Maybe because you don't have installed this module by composer.
If you want to fix it you have to reinstall this module but this time by composer or you can only require missing dependence like this :
```composer require google/apiclient ~1.1.0```

**Comment by ngweb37** [comment]
Thanks, but is there a way to install GoogleApiClient without using composer ? I uploaded apiclient folder in core/vendor/google/, reinstalled the module GoogleShopping, but the same error appears ?

**Comment by lopes-vincent** [comment]
No it's not possible because in this case the autoloader can't be generated correctly. 
But why you don't want to install it with composer ?
You have just to download this file : https://getcomposer.org/composer.phar put it in your thelia root and then run ```php composer.phar require thelia/google-shopping-module```
